# Nama program yang akan dijalankan
PROGRAMS = alpro3 alpro4

# Nama file sumber dan target
alpro3_src = C:\Dev\kuliah\semester_01\AlPro\pertemuan3.cpp
alpro3_target = C:\Dev\kuliah\execute\pertemuan3.exe

# Perintah kompilasi dan opsi
CC = g++

# Target default jika tidak ada argumen yang diberikan
default: help

# Target untuk menjalankan program dengan argumen
run: 
	@echo "Usage: make run [program]"
	@echo "Available programs: $(PROGRAMS)"

run-%: 
	@if [ -f $* ]; then \
		./$*; \
	else \
		echo "Program '$*' not found"; \
	fi

# Aturan untuk membuat target alpro3
alpro3: $(alpro3_target)

$(alpro3_target): $(alpro3_src)
	$(CC) $(alpro3_src) -o $(alpro3_target)

# Aturan clean untuk menghapus file target
clean:
	rm -f $(alpro3_target)

# Target untuk menampilkan bantuan
help:
	@echo "Usage: make run [program]"
	@echo "Available programs: $(PROGRAMS)"